name: Test
on: [push]
jobs:
  echo_hello_world:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "hello world!!"
  echo_new_world:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "new world!!"
